// @ts-check
// `@type` JSDoc annotations allow editor autocompletion and type checking
// (when paired with `@ts-check`).
// There are various equivalent ways to declare your Docusaurus config.
// See: https://docusaurus.io/docs/api/docusaurus-config
import { themes as prismThemes } from "prism-react-renderer";

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)
const siteURL = process.env.SITE_URL || "http://localhost:3000";
const rawBaseUrl = process.env.BASE_URL;
const normalizedBaseUrl =
  rawBaseUrl === undefined
    ? "/"
    : rawBaseUrl.endsWith("/")
    ? rawBaseUrl
    : rawBaseUrl + "/";

const {
  transformImportedContent,
} = require("./src/utils/communityDocsTransforms");
const {
  deriveHelpers,
  createCommunityEditUrl,
} = require("./src/utils/communityDocsConfig");

// Custom fields configuration
const customFields = {
  communityDocs: {
    // Single source of truth: remote docs with optional front matter additions
    remoteDocs: [
      // No changes
      { origFilename: "blog-topics.md" },
      { origFilename: "code-of-conduct.md" },
      { origFilename: "communication.md" },
      { origFilename: "MAINTAINERS.md" },
      { origFilename: "incubator.md" },
      { origFilename: "stable-repo-charts-new-locations.md" },
      { origFilename: "user-profiles.md" },

      { origFilename: "hips/README.md" },
      { origFilename: "hips/hip-0001.md" },
      { origFilename: "hips/hip-0002.md" },
      { origFilename: "hips/hip-0003.md" },
      { origFilename: "hips/hip-0004.md" },
      { origFilename: "hips/hip-0005.md" },
      { origFilename: "hips/hip-0006.md" },
      { origFilename: "hips/hip-0007.md" },
      { origFilename: "hips/hip-0008.md" },
      { origFilename: "hips/hip-0009.md" },
      { origFilename: "hips/hip-0010.md" },
      { origFilename: "hips/hip-0011.md" },
      { origFilename: "hips/hip-0012.md" },
      { origFilename: "hips/hip-0014.md" },
      { origFilename: "hips/hip-0015.md" },
      { origFilename: "hips/hip-0016.md" },
      { origFilename: "hips/hip-0017.md" },
      { origFilename: "hips/hip-0018.md" },
      { origFilename: "hips/hip-0019.md" },
      { origFilename: "hips/hip-0020.md" },
      { origFilename: "hips/hip-0021.md" },
      { origFilename: "hips/hip-0022.md" },
      { origFilename: "hips/hip-0023.md" },
      { origFilename: "hips/hip-0024.md" },
      { origFilename: "hips/hip-0025.md" },
      { origFilename: "hips/hip-0026.md" },

      { origFilename: "hips/archives/README.md" },
      { origFilename: "hips/archives/monocular/1.0-improvements.md" },
      { origFilename: "hips/archives/helm/distributed-search.md" },
      { origFilename: "hips/archives/helm/helm-v3/000-helm-v3.md" },
      { origFilename: "hips/archives/helm/helm-v3/001-charts.md" },
      { origFilename: "hips/archives/helm/helm-v3/002-events.md" },
      { origFilename: "hips/archives/helm/helm-v3/003-state.md" },
      { origFilename: "hips/archives/helm/helm-v3/004-hooks.md" },
      { origFilename: "hips/archives/helm/helm-v3/005-plugins.md" },
      { origFilename: "hips/archives/helm/helm-v3/006-repositories.md" },
      { origFilename: "hips/archives/helm/helm-v3/007-security.md" },
      { origFilename: "hips/archives/helm/helm-v3/008-controller.md" },
      { origFilename: "hips/archives/helm/helm-v3/009-package_manager.md" },
      { origFilename: "hips/archives/helm/helm-v3/010-removed.md" },
      { origFilename: "hips/archives/helm/helm-v3/011-user_stories.md" },
      { origFilename: "hips/archives/helm/helm-v3/012-chart-dev-stories.md" },
      {
        origFilename:
          "hips/archives/helm/helm-v3/research/package-manager-ux.md",
      },

      { origFilename: "art/readme.md", meta: { title: "Styleguide" } },

      { origFilename: "meeting-notes/2017.txt" },
      { origFilename: "meeting-notes/2018.txt" },
      { origFilename: "meeting-notes/2019.txt" },
      { origFilename: "meeting-notes/2020.txt" },
      { origFilename: "meeting-notes/2021.txt" },

      // Changes to imported files
      {
        origFilename: "README.md",
        meta: {
          sidebar_position: 1,
        },
      },
      {
        origFilename: "SECURITY.md",
        meta: {
          sidebar_label: "Helm Security",
        },
      },
      {
        origFilename: "governance/README.md",
        meta: {
          sidebar_label: "Governance",
          title: "Governance Introduction",
          // The frontmatter id key should match the id in community/governance/_category_.json
          // in order for this file to be the category landing page.
          // We only need this if we want to keep the other imported file's original filepath
          // as governance/governance.md. Because a filename matching it's category is the
          // default landing page for that category (then index.md/x, then README), unless
          // overridden by an id.
          // See: https://docusaurus.io/docs/3.8.1/sidebar/autogenerated#category-index-convention
          id: "helm-governance",
          // Make this the last item
          sidebar_position: 9,
        },
      },
      {
        origFilename: "governance/governance.md",
        meta: {
          sidebar_label: "Rules",
          title: "Governance Rules",
          slug: "governance",
        },
      },
    ],
    // Exceptions for specific files/links → force target href
    // Keys are source filenames; inner keys are original hrefs; values are desired hrefs
    linkExceptions: {
      "README.md": {
        "https://github.com/helm/community/tree/main/art": "/community/art",
      },
      "governance/README.md": {
        "governance.md": "/community/governance/governance",
        "../MAINTAINERS.md": "/community/MAINTAINERS",
      },
      "hips/hip-0005.md": {
        "https://github.com/helm/community/blob/master/governance/governance.md":
          "/community/governance/governance",
      },
      "hips/hip-0007.md": {
        "https://github.com/helm/community/blob/master/governance/governance.md":
          "/community/governance/governance",
        // To-do: is there a way to import maintainer-groups.yaml into docusaurus?
        "../maintainer-groups.yaml":
          "https://github.com/helm/community/blob/main/maintainer-groups.yaml",
      },
      "hips/hip-0009.md": {
        "../security.md": "../SECURITY.md",
      },
      "hips/hip-0012.md": {
        "https://github.com/helm/community/blob/main/user-profiles.md":
          "/community/user-profiles",
      },
      "hips/hip-0014.md": {
        "https://github.com/helm/community/tree/main/governance":
          "/community/governance/governance",
        // To-do: is there a way to import maintainer-groups.yaml into docusaurus?
        "https://github.com/helm/community/blob/main/Teams.md":
          "https://github.com/helm/community/blob/main/maintainer-groups.yaml",
      },
      "hips/hip-0025.md": {
        "https://github.com/helm/community/blob/main/user-profiles.md":
          "/community/user-profiles",
      },
      "hips/hip-0026.md": {
        "https://github.com/helm/community/blob/main/hips/hip-0012.md":
          "/community/hips/hip-0012",
        "https://github.com/helm/community/blob/main/hips/archives/helm/distributed-search.md":
          "/community/hips/archives/helm/distributed-search",
      },
      "hips/archives/monocular/1.0-improvements.md": {
        "https://github.com/helm/community/blob/master/proposals/distributed-search.md":
          "/community/hips/archives/helm/distributed-search",
      },
      // To-do: fix these broken links upstream
      "SECURITY.md": {
        // Anchors present in source links (eg, #how-can-i-help) will be appended automatically
        "README.md": "/community",
      },
      "hips/archives/helm/helm-v3/000-helm-v3.md": {
        "../../../user-profiles.md": "../../../../user-profiles.md",
      },
      "hips/archives/helm/helm-v3/011-user_stories.md": {
        "../user-profiles.md": "../../../../user-profiles.md",
      },
    },
  },
};

// Derive helpers from community docs configuration
const { remoteDocPaths, metaByPath, slugByPath } = deriveHelpers(
  customFields.communityDocs.remoteDocs
);
const linkExceptions = customFields.communityDocs.linkExceptions;

/** @type {import('@docusaurus/types').Config} */
const config = {
  title: "Helm",
  tagline: "The package manager for Kubernetes",
  favicon: "img/favicon.ico",

  customFields: customFields,

  // Future flags, see https://docusaurus.io/docs/api/docusaurus-config#future
  future: {
    v4: true, // Improve compatibility with the upcoming Docusaurus v4
  },

  // Opt-in to less strict, standard CommonMark support with options
  // Automatically detects .md and .mdx extensions
  // See https://docusaurus.io/docs/markdown-features/react#markdown-and-jsx-interoperability
  // See https://github.com/prettier/prettier/issues/17089
  markdown: {
    format: "detect",
  },

  // Set the production url of your site here
  url: siteURL,
  // Set the /<baseUrl>/ pathname under which your site is served
  // For GitHub pages deployment, it is often '/<projectName>/'
  baseUrl: normalizedBaseUrl,

  // GitHub pages deployment config.
  // If you aren't using GitHub pages, you don't need these.
  organizationName: "helm", // Usually your GitHub org/user name.
  projectName: "helm-www", // Usually your repo name.

  onBrokenLinks: "throw",

  i18n: {
    defaultLocale: "en",
    locales: ["en", "de", "el", "es", "fr", "ja", "ko", "pt", "ru", "uk", "zh"],
    localeConfigs: {
      en: {
        htmlLang: "en-us",
        label: "English",
      },
      de: {
        label: "Deutsch (German)",
      },
      es: {
        label: "Español (Spanish)",
      },
      fr: {
        label: "Français (French)",
      },
      el: {
        label: "Ελληνικά (Greek)",
      },
      ja: {
        label: "日本語 (Japanese)",
      },
      ko: {
        label: "한국어 (Korean)",
      },
      pt: {
        label: "Português (Portuguese)",
      },
      ru: {
        label: "Русский (Russian)",
      },
      uk: {
        label: "Українська (Ukrainian)",
      },
      zh: {
        label: "中文 (Chinese)",
      },
    },
  },

  presets: [
    [
      "classic",
      /** @type {import('@docusaurus/preset-classic').Options} */
      ({
        docs: {
          sidebarPath: "./sidebars.js",
          // Please change this to your repo.
          // Remove this to remove the "edit this page" links.
          editUrl: "https://github.com/helm/helm-www/blob/main/",
          // Links "edit this page" on translated pages to i18n/[LOCALE]/... instead of English source file
          editLocalizedFiles: true,
          // "lastVersion" means the latest release
          lastVersion: "current",
          versions: {
            // v4 is "current"
            // v3 is in /versioned_docs/version-3
            // v2 is in /versioned_docs/version-2
            // TODO when we start work on Helm v5, we will copy /docs to /versioned_docs/version-4
            // and v5 will then live in /docs
            // Be sure to update each locale's docusaurus-plugin-content-docs/current.json to match the current label
            // To-do: add this snippet to automation for bumping the version for each new release:
            // `for f in i18n/*/docusaurus-plugin-content-docs/current.json; do jq '."version.label".message = "4.0.0"' "$f" > "$f.tmp" && mv "$f.tmp" "$f"; done`
            current: { label: "4.0.0" },
            3: { label: "3.19.0", path: "v3" },
            2: { label: "2.17.0", path: "v2" },
          },
        },
        blog: {
          showReadingTime: true,
          blogSidebarTitle: "All posts",
          blogSidebarCount: "ALL",
          feedOptions: {
            type: ["rss", "atom"],
            xslt: true,
          },
          // Please change this to your repo.
          // Remove this to remove the "edit this page" links.
          editUrl: "https://github.com/helm/helm-www/blob/main/",
          // Useful options to enforce blogging best practices
          onInlineTags: "warn",
          onInlineAuthors: "warn",
          onUntruncatedBlogPosts: "throw",
        },
        theme: {
          customCss: "./src/css/custom.css",
        },
      }),
    ],
  ],

  // Note @docusaurus/preset-classic already includes a docs plugin instance for us under "presets"
  // See https://docusaurus.io/docs/docs-multi-instance#versioned-and-unversioned-doc
  plugins: [
    [
      "@docusaurus/plugin-content-docs",
      {
        id: "community",
        path: "community",
        routeBasePath: "community",
        sidebarPath: "./sidebars_community.js",
        editLocalizedFiles: true,
        editUrl: createCommunityEditUrl(remoteDocPaths),
        numberPrefixParser: false,
      },
    ],
    [
      "docusaurus-plugin-remote-content",
      {
        name: "community",
        sourceBaseUrl:
          "https://raw.githubusercontent.com/helm/community/refs/heads/main/",
        outDir: "community",
        documents: remoteDocPaths,
        // Set to true since we commit files to Git and performCleanup: false prevents deletion
        noRuntimeDownloads: true,
        // Must be false to prevent files being deleted between i18n locale builds
        // See: https://github.com/rdilweb/docusaurus-plugin-remote-content/issues/98
        performCleanup: false,
        modifyContent(filename, content) {
          const transformed = transformImportedContent(
            filename,
            content,
            metaByPath,
            slugByPath,
            linkExceptions
          );

          // transformImportedContent now returns an object with content and optionally filename
          return transformed;
        },
      },
    ],
  ],

  themeConfig:
    /** @type {import('@docusaurus/preset-classic').ThemeConfig} */
    ({
      algolia: {
        appId: "AYED2EXU9K",
        apiKey: "ab452074863b15ae08d14d22d393f1e0",
        indexName: "production",
      },
      announcementBar: {
        backgroundColor: "#0f1689",
        textColor: "#ffffff",
        // Note that closed state is stored in browser
        // Change id to show again for users who have already closed it
        id: "helm4_ga",
        content:
          '🎉 Helm v4.0.0 is out! See the <a href="/docs/overview">Helm 4 Overview</a> for details!',
        isCloseable: true,
      },
      // Replace with your project's social card
      image: "img/helm-social-card.png",
      colorMode: {
        defaultMode: "light",
        disableSwitch: true,
      },
      docs: {
        sidebar: {
          hideable: true,
          autoCollapseCategories: true,
        },
      },
      navbar: {
        title: "Helm",
        logo: {
          alt: "Helm Logo",
          src: "img/helm.svg",
        },
        items: [
          { to: "docs", label: "Docs", position: "left" },
          { to: "community", label: "Community", position: "left" },
          { to: "blog", label: "Blog", position: "left" },
          {
            href: "https://artifacthub.io/",
            label: "Charts",
            position: "left",
          },
          {
            type: "docsVersionDropdown",
            position: "right",
          },
          {
            type: "localeDropdown",
            position: "right",
          },
        ],
      },
      footer: {
        style: "dark",
        links: [
          {
            title: "Helm Project",
            items: [
              {
                label: "Source code",
                href: "https://github.com/helm/helm",
              },
              {
                label: "Blog",
                to: "blog",
              },
              {
                label: "Events",
                href: "https://www.cncf.io/community/kubecon-cloudnativecon-events/",
              },
              {
                label: "Code of Conduct",
                href: "https://github.com/cncf/foundation/blob/master/code-of-conduct.md",
              },
            ],
          },
          {
            title: "Charts",
            items: [
              {
                label: "Introduction",
                to: "docs/intro",
              },
              {
                label: "Chart tips & tricks",
                to: "docs/howto/charts_tips_and_tricks",
              },
              {
                label: "Developing Charts",
                to: "docs/topics/charts",
              },
              {
                label: "Search 800+ Charts",
                href: "https://artifacthub.io/",
              },
            ],
          },
          {
            title: "Development",
            items: [
              {
                label: "Slack (#helm-dev)",
                href: "https://kubernetes.slack.com/messages/C51E88VDG",
              },
              {
                label: "Contribution Guide",
                href: "https://github.com/helm/helm/blob/main/CONTRIBUTING.md",
              },
              {
                label: "Maintainers",
                href: "https://github.com/helm/helm/blob/main/OWNERS",
              },
              {
                label: "Weekly Meetings",
                href: "https://github.com/helm/community/blob/main/communication.md#meetings",
              },
            ],
          },
          {
            title: "Community",
            items: [
              {
                label: "GitHub Community",
                href: "https://github.com/helm/community",
              },
              {
                label: "Slack (#helm-users)",
                href: "https://kubernetes.slack.com/",
              },
              {
                label: "Stack Overflow",
                href: "https://stackoverflow.com/questions/tagged/kubernetes-helm",
              },
              {
                label: "X",
                href: "https://x.com/helmpack",
              },
            ],
          },
        ],
        logo: {
          alt: "CNCF Logo",
          src: "/img/cncf-white.png",
        },
        copyright: `<p>We are a <a href="https://www.cncf.io/">Cloud Native Computing Foundation</a> graduated project.</p><p>© Helm Authors ${new Date().getFullYear()}. Documentation distributed under <a href="https://creativecommons.org/licenses/by/4.0">CC-BY-4.0.</a></p><p>© ${new Date().getFullYear()} The Linux Foundation. All rights reserved. The Linux Foundation has registered trademarks and uses trademarks. For a list of trademarks of The Linux Foundation, please see our <a href="https://www.linuxfoundation.org/trademark-usage/">Trademark Usage page</a>.</p>`,
      },
      prism: {
        theme: prismThemes.github,
        darkTheme: prismThemes.dracula,
        additionalLanguages: ["bash"],
      },
    }),

  clientModules: [
    require.resolve("./src/client-modules/heroHeightCalculator.js"),
  ],
};

export default config;
