// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebarsCommunity = {
  // Default, auto generates a sidebar from folder structure
  communitySidebar: [{ type: "autogenerated", dirName: "." }],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebarsCommunity;
