#!/usr/bin/env bash
set -e
set -x

export APP="helm-www"

sudo apt-get install --assume-yes openjdk-7-jre
gem install bundler -v "~> 1.10" --conservative --no-ri --no-rdoc
bundle install
sudo npm install -g gulp
npm install
gulp
bundle exec jekyll build
bundle exec s3_website cfg apply
bundle exec s3_website push --force