apiVersion: v1
kind: Pod
metadata:
  name: "{{ template "nginx.fullname" . }}-service-test"
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/name: {{ template "nginx.name" . }}
  annotations:
    "helm.sh/hook": test-success
spec:
  containers:
    - name: curl
      image: radial/busyboxplus:curl
      command: ['curl']
      args:  ['{{ template "nginx.fullname" . }}:{{ .Values.service.port }}']
  restartPolicy: Never
